spring:
  application:
    name: datt

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  datasource:
    url: ${DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  batch:
    job:
      enabled: false

public-data:
  place:
    base-url: https://apis.data.go.kr
    endpoint: /B553077/api/open/sdsc2/storeListInUpjong
    service-key: ${PUBLIC_DATA_SERVICE_KEY}
    num-of-rows: 1000
    type: json

jwt:
  secret: ${JWT_SECRET}